### PR TITLE
Fix when login items list is empty

### LINKED ISSUE #29: Login item of App is not added if login items list is empty.
If login items is empty, couldn't add login item.

image

### PR DESCRIPTION
**Pull request by dimitarnestorov**
Fixes #29

Passing `nil` seems to work fine. However Swift complains since the argument is not optional hence the `unsafeBitCast`.

### CODE REVIEW

File: Lib/LoginServiceKit/LoginServiceKit.swift [hunk 1]
```diff
@@ -65,9 +65,11 @@ public final class LoginServiceKit: NSObject {
         guard isExistLoginItems(at: path) == false else {
             return false
         }
-        guard let (list, items) = snapshot, let item = items.last else {
+        guard let (list, items) = snapshot else {
             return false
         }
+        
+        let item = unsafeBitCast(items.last ?? nil, to: LSSharedFileListItem.self)
```
Comment (Econa77) [inline Lib/LoginServiceKit/LoginServiceKit.swift:72]:
```suggestion
        let item = unsafeBitCast(items.last, to: LSSharedFileListItem.self)
```

Comment (Econa77) [reply Lib/LoginServiceKit/LoginServiceKit.swift:72]: @dimitarnestorov Thanks for the PR 👍 It worked correctly in my environment.
Can you please incorporate Suggested Change?

**Review by Econa77 — APPROVED** [review]
Thanks 👍

**Comment by Econa77** [comment]
Released [v2.4.0](https://github.com/Clipy/LoginServiceKit/releases/tag/v2.4.0).
